flush ruleset
table inet segmentation {
  chain forward {
    type filter hook forward priority 0; policy drop;
    ct state established,related accept
    iifname "eth6" oifname { "eth2", "eth3", "eth4", "eth5", "eth7", "eth8" } tcp dport 22 accept comment "management-admin"
    iifname { "eth2", "eth3", "eth4" } oifname "eth5" tcp dport { 443, 445 } accept comment "business-to-servers"
    iifname { "eth2", "eth3", "eth4", "eth5", "eth6", "eth7", "eth8" } oifname "eth5" udp dport 53 accept comment "central-dns"
    iifname "eth7" oifname "eth8" tcp dport { 80, 443 } accept comment "guest-to-dmz-web"
    iifname "eth8" oifname "eth5" tcp dport 443 accept comment "dmz-to-approved-server"
    counter log prefix "NF_SEGMENT_DENY " drop
  }
}
