import { notFound } from "next/navigation";
import { verifyLetter } from "@/lib/letter-sig";
import { LetterContent } from "./letter-content";

// Server-side gate: only renders when the URL carries a valid HMAC signature
// generated by signLetter() at email-send time. Without it, anyone could
// craft ?name=Random%20Person&track=Whatever and produce a forgery that
// looked identical to a real acceptance letter.
//
// On any failure (missing params, bad sig, sig length mismatch) we 404.
// We deliberately do NOT distinguish "no sig" from "wrong sig" in the
// response — both look like a missing page so an attacker can't probe.
export default async function AcceptanceLetterPage({
  searchParams,
}: {
  searchParams: Promise<{ name?: string; track?: string; sig?: string }>;
}) {
  const { name, track, sig } = await searchParams;

  if (!name || !track || !sig) notFound();
  if (!verifyLetter(name, track, sig)) notFound();

  return <LetterContent name={name} track={track} />;
}
