Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant", disabled: false

  { "vulnerable" => "192.168.77.21", "patched" => "192.168.77.22" }.each do |name, address|
    config.vm.define name do |node|
      node.vm.hostname = "nf-eh-a2-#{name}"
      node.vm.network "private_network", ip: address
      node.vm.provider "virtualbox" do |provider|
        provider.memory = 2048
        provider.cpus = 2
      end
      node.vm.provision "shell", path: "provision.sh", args: [name]
    end
  end
end
